# Data Quality Rules Configuration

# Common rules applied to all indicators
common_rules:
  # Value must be a valid number (not null, N/A, etc.)
  value_type:
    type: "number"
    allow_null: false
    description: "Value must be a valid number"
  
  # Date must be in a valid format
  date_format:
    format: "YYYY-MM-DD"
    description: "Date must be in YYYY-MM-DD format"
  
  # Record must have required fields
  required_fields:
    fields: ["series_id", "ref_date", "value"]
    description: "Record must contain all required fields"

# Indicator-specific rules
indicators:
  usdbrl:
    # Value must be greater than zero
    positive_value:
      min_value: 0
      description: "Exchange rate must be positive"
    
    # Value shouldn't have extreme variations
    variation_check:
      max_daily_pct_change: 10.0  # 10%
      description: "Daily change exceeding 10% will be flagged for review"
  
  selic:
    # Selic rate typically ranges from 2% to 20%
    range_check:
      min_value: 0
      max_value: 25
      description: "Selic rate should be between 0% and 25%"
  
  ipca:
    # IPCA typically ranges from -1% to 3% monthly
    range_check:
      min_value: -1.0
      max_value: 3.0
      description: "Monthly IPCA should be between -1% and 3%"

# Quarantine configuration
quarantine:
  enabled: true
  notify_on_quarantine: true
  location: "s3://dl-prod/quarantine/{indicator}/"
  notification:
    method: "sns"
    topic_arn: "arn:aws:sns:us-east-1:123456789012:data-quality-alerts"
